import * as THREE from 'three';
import { EffectComposer } from 'https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/postprocessing/EffectComposer.js';
import { RenderPass } from 'https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/postprocessing/UnrealBloomPass.js';
import createCartoonWorld from './cartoonWorld.js';

const $ = (s) => document.querySelector(s);
const panel = $('#panel'), panelContent = $('#panel-content'), hint = $('#hint');
const sector = $('#sector'), speedEl = $('#speed'), questTitle = $('#quest-title'), questCopy = $('#quest-copy');
const progressEl = $('#progress-count'), boardState = $('#board-state'), challenge = $('#challenge'), challengeContent = $('#challenge-content');
const mobile = matchMedia('(pointer: coarse)').matches;
let content;
try { content = await fetch('data/content.json').then(r => r.json()); } catch { content = {profile:{name:'Flood Sung',role:'AI Researcher. Robotics Founder. Agent Systems Builder.',summary:'Founder & CEO of XVI Robotics.'},research:[],publications:[],opensource:{},career:[],contact:{}}; }

const scene = new THREE.Scene();
scene.background = new THREE.Color(0x081126); scene.fog = new THREE.FogExp2(0x0d1b38, .026);
const camera = new THREE.PerspectiveCamera(52, innerWidth / innerHeight, .1, 500); camera.position.set(0, 9, 18);
const renderer = new THREE.WebGLRenderer({ antialias:true, powerPreference:'high-performance' });
renderer.setPixelRatio(Math.min(devicePixelRatio, mobile ? 1.15 : 1.65)); renderer.setSize(innerWidth, innerHeight);
renderer.outputColorSpace = THREE.SRGBColorSpace; renderer.toneMapping = THREE.ACESFilmicToneMapping; renderer.toneMappingExposure = 1.12;
renderer.shadowMap.enabled = true; renderer.shadowMap.type = THREE.PCFSoftShadowMap; $('#scene').appendChild(renderer.domElement);
const composer = new EffectComposer(renderer); composer.addPass(new RenderPass(scene, camera));
composer.addPass(new UnrealBloomPass(new THREE.Vector2(innerWidth, innerHeight), .28, .5, .86));
scene.add(new THREE.HemisphereLight(0x9fb9e8, 0x10172e, 1.65));
const fill = new THREE.DirectionalLight(0xffe4bf, 1.25); fill.position.set(-20, 30, 18); fill.castShadow = true; fill.shadow.mapSize.set(1024,1024); scene.add(fill);
const rim = new THREE.PointLight(0x63eaff, 16, 90); rim.position.set(0, 12, -18); scene.add(rim);

function seeded(i){const x=Math.sin(i*12.9898+78.233)*43758.5453;return x-Math.floor(x)}
function makeStars(){const n=4200,p=new Float32Array(n*3),c=new Float32Array(n*3);for(let i=0;i<n;i++){const a=seeded(i)*Math.PI*2,r=100+seeded(i+1)*230;p[i*3]=Math.cos(a)*r;p[i*3+1]=20+seeded(i+2)*150;p[i*3+2]=Math.sin(a)*r-80;const col=new THREE.Color().setHSL(.56+seeded(i+3)*.1,.55,.65);c.set(col.toArray(),i*3)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(p,3));g.setAttribute('color',new THREE.BufferAttribute(c,3));scene.add(new THREE.Points(g,new THREE.PointsMaterial({size:.65,vertexColors:true,transparent:true,opacity:.72})));} makeStars();
const world = createCartoonWorld(scene); const landmarks = Object.fromEntries(world.landmarks.map(x => [x.userData.slug, x]));

function toon(color){return new THREE.MeshToonMaterial({color});}
function makePlayer(){const p=new THREE.Group();p.name='PX-01 Explorer';
  const body=new THREE.Mesh(new THREE.CapsuleGeometry(1.05,1.25,8,16),toon(0x70a9ca));body.position.y=1.55;body.castShadow=true;p.add(body);
  const visor=new THREE.Mesh(new THREE.SphereGeometry(.62,24,16,0,Math.PI*2,0,Math.PI*.58),new THREE.MeshStandardMaterial({color:0x132744,metalness:.3,roughness:.17,emissive:0x174d69,emissiveIntensity:.7}));visor.position.set(0,2.2,.42);visor.rotation.x=-.15;p.add(visor);
  const pack=new THREE.Mesh(new THREE.BoxGeometry(1.25,.82,.36),toon(0x263958));pack.position.set(0,1.32,-.62);pack.castShadow=true;p.add(pack);
  const antenna=new THREE.Mesh(new THREE.CylinderGeometry(.07,.07,.65,10),toon(0xffc86d));antenna.position.set(0,3.15,0);p.add(antenna);const lamp=new THREE.Mesh(new THREE.SphereGeometry(.14,12,8),new THREE.MeshBasicMaterial({color:0xffd77d}));lamp.position.y=3.5;p.add(lamp);
  const feet=[];for(const x of [-.55,.55]){const foot=new THREE.Mesh(new THREE.SphereGeometry(.42,16,10),toon(0x355779));foot.position.set(x,.35,.08);foot.scale.z=1.35;foot.castShadow=true;p.add(foot);feet.push(foot);}p.userData.feet=feet;scene.add(p);return p;}
const player=makePlayer(); player.position.set(0,0,0);

const labels={};
for(const [slug,obj] of Object.entries(landmarks)){const b=document.createElement('button');b.className='node-label';b.textContent=obj.userData.title||slug.toUpperCase();b.dataset.slug=slug;b.onclick=()=>travelTo(slug);document.body.appendChild(b);labels[slug]=b;}
function placeLabels(){for(const [slug,obj] of Object.entries(landmarks)){const pos=obj.position.clone().add(new THREE.Vector3(0,7,0)).project(camera);const d=camera.position.distanceTo(obj.position);const visible=pos.z>-1&&pos.z<1&&d<90&&Math.abs(pos.x)<.9&&Math.abs(pos.y)<.82;labels[slug].style.display=visible?'block':'none';if(visible){labels[slug].style.left=`${(pos.x+1)*innerWidth/2}px`;labels[slug].style.top=`${(1-pos.y)*innerHeight/2}px`;labels[slug].style.opacity=Math.max(.35,1-d/90)}}}

const paperFor={compare:0,proof:3,agent:2}; const completed=new Set(JSON.parse(localStorage.getItem('xviResearchProgress')||'[]'));
function refreshProgress(){progressEl.textContent=`${completed.size} / 3`;boardState.textContent=completed.size===3?'UNLOCKED':'LOCKED';if(completed.size===3){questTitle.textContent='Concept Board complete';questCopy.textContent='You mapped the first research thread. The archive is open.'}}
refreshProgress();
function paperCard(slug){const p=content.publications[paperFor[slug]]||content.publications[0];return `<div class="eyebrow">PAPER CARD / VERIFIED SIGNAL</div><h2>${p.title}</h2><p>${p.year} · ${p.citations} citations in the ${content.retrievedAt} Scholar snapshot.</p><div class="meta">The scan is linked to the real publication record. Read the abstract and source at the archive.</div><p><a href="${p.url}" target="_blank" rel="noreferrer">OPEN PAPER ↗</a></p>`}
const challengeData={compare:{title:'Compare the signals',copy:'Relation Networks learn by comparing examples. Pick the action that matches the idea behind this paper.',answers:['Compare two examples to measure their relation','Hide every example and guess randomly','Only train on one permanent class'],correct:0},proof:{title:'Route the proof',copy:'The proof theatre rewards a path that is checkable step by step.',answers:['Follow a valid chain of premises','Skip the premises and jump to the result','Choose the brightest tile'],correct:0},agent:{title:'Deploy the agent',copy:'An agent needs a grounded action loop. Choose the useful sequence.',answers:['Observe → plan → act → verify','Act forever without observing','Only display a static answer'],correct:0}};
function openChallenge(slug){const d=challengeData[slug];challengeContent.innerHTML=`<div class="eyebrow">FIELD CHALLENGE / ${slug.toUpperCase()}</div><h3>${d.title}</h3><p>${d.copy}</p><div class="choices">${d.answers.map((a,i)=>`<button data-answer="${i}">${a}</button>`).join('')}</div>`;challenge.classList.add('open');challengeContent.querySelectorAll('[data-answer]').forEach(btn=>btn.onclick=()=>{if(Number(btn.dataset.answer)===d.correct){completed.add(slug);localStorage.setItem('xviResearchProgress',JSON.stringify([...completed]));refreshProgress();challenge.classList.remove('open');openPanel('paper-'+slug)}})}
challenge.querySelector('.close-challenge').onclick=()=>challenge.classList.remove('open');
function openPanel(key){if(key.startsWith('paper-')){panelContent.innerHTML=paperCard(key.slice(6));panel.classList.add('open');return;}let html='';if(key==='profile')html=`<div class="eyebrow">CENTRAL STUDIO / PROFILE</div><h2>${content.profile.name}</h2><p>${content.profile.role}</p><p>${content.profile.summary}</p><div class="metric-row">${Object.entries(content.profile.metrics||{}).map(([k,v])=>`<div class="metric"><strong>${v}</strong><span>${k.replace(/([A-Z])/g,' $1').toUpperCase()}</span></div>`).join('')}</div>`;else if(key==='archive')html=`<div class="eyebrow">ARCHIVE HALL / PUBLICATIONS</div><h2>SELECTED SIGNALS</h2><p>Every card is driven by a dated Google Scholar snapshot. Citation counts change over time.</p>${content.publications.map(p=>`<p><a href="${p.url}" target="_blank" rel="noreferrer"><strong>${p.title}</strong></a><br>${p.year} · ${p.citations} citations</p>`).join('')}`;else if(key==='opensource')html=`<div class="eyebrow">OPEN SOURCE FOUNDRY</div><h2>TOOLS IN THE WILD</h2><p>${content.opensource.summary}</p><div class="meta">${(content.opensource.repoDetails||[]).map(r=>`<a href="${r.url}" target="_blank" rel="noreferrer">${r.name}</a> · ${r.stars}★<br>`).join('')}<br>${content.opensource.stats.stars} stars · ${content.opensource.stats.repos} repositories</div>`;else if(key==='career')html=`<div class="eyebrow">CAREER CAMPUS</div><h2>RESEARCH · SYSTEMS · COMPANY BUILDING</h2><p>${content.career.join('\n')}</p>`;else html=`<div class="eyebrow">COMMS LIGHTHOUSE</div><h2>OPEN CHANNEL</h2><p>For research collaboration, speaking, media, or company-building conversations.</p><div class="meta">EMAIL  ${content.contact.email}<br>GITHUB  github.com/floodsung<br>SCHOLAR  s11zFYQAAAAJ</div><p><a href="mailto:${content.contact.email}">TRANSMIT EMAIL ↗</a></p>`;panelContent.innerHTML=html;panel.classList.add('open');}

let yaw=0.08,camDistance=13,drag=false,lastX=0,lastY=0;const keys={};let targetTravel=null;
function travelTo(slug){if(landmarks[slug]){targetTravel=landmarks[slug].position.clone().add(new THREE.Vector3(0,0,8));panel.classList.remove('open');sector.textContent=slug==='compare'?'COMPARE LAB':slug==='proof'?'PROOF LIBRARY':slug==='agent'?'AGENT FOUNDRY':'CENTRAL STUDIO';}else openPanel(slug)}
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key==='Escape'){panel.classList.remove('open');challenge.classList.remove('open')}if(e.key.toLowerCase()==='e'){const near=nearest();if(near)openChallenge(near)}if(e.key===' '){e.preventDefault();if(player.position.y<.05)jumpVelocity=7.4}});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);addEventListener('blur',()=>Object.keys(keys).forEach(k=>keys[k]=false));
renderer.domElement.addEventListener('pointerdown',e=>{drag=true;lastX=e.clientX;lastY=e.clientY;renderer.domElement.setPointerCapture(e.pointerId)});renderer.domElement.addEventListener('pointermove',e=>{if(!drag)return;yaw-=(e.clientX-lastX)*.006;lastX=e.clientX;lastY=e.clientY});renderer.domElement.addEventListener('pointerup',()=>drag=false);
let jumpVelocity=0;let paused=false;function nearest(){let best=null,dist=Infinity;for(const [slug,obj] of Object.entries(landmarks)){const d=player.position.distanceTo(obj.position);if(d<dist){dist=d;best=slug}}return dist<9?best:null}
window.__THREE_GAME_TEST_HOOKS__={setState(state){if(state==='active-play'){player.position.set(0,0,0);targetTravel=null;panel.classList.remove('open');challenge.classList.remove('open');}if(state==='compare-near'){player.position.copy(landmarks.compare.position).add(new THREE.Vector3(0,0,8));}return {state}},setPausedForScreenshot(value){paused=Boolean(value)}};
document.querySelectorAll('[data-node]').forEach(b=>b.onclick=()=>{const n=b.dataset.node;if(n==='compare'||n==='reasoning'||n==='agent')travelTo(n==='reasoning'?'proof':n);else if(n==='profile')openPanel('profile');else if(n==='archive')openPanel('archive');});
function loop(t){requestAnimationFrame(loop);const dt=Math.min(.04,(t-(loop.last||t))/1000);loop.last=t;const move=new THREE.Vector3();if(!paused){if(keys.w||keys.arrowup)move.z-=1;if(keys.s||keys.arrowdown)move.z+=1;if(keys.a||keys.arrowleft)move.x-=1;if(keys.d||keys.arrowright)move.x+=1;if(move.lengthSq())move.normalize();const dash=keys.shift?2.2:1;move.applyAxisAngle(new THREE.Vector3(0,1,0),yaw);player.position.x+=move.x*dt*7*dash;player.position.z+=move.z*dt*7*dash;player.position.x=THREE.MathUtils.clamp(player.position.x,-26,26);player.position.z=THREE.MathUtils.clamp(player.position.z,-27,24);jumpVelocity-=dt*18;player.position.y=Math.max(0,player.position.y+jumpVelocity*dt);if(player.position.y===0)jumpVelocity=0;player.rotation.y=move.lengthSq()?Math.atan2(move.x,move.z):player.rotation.y;player.userData.feet.forEach((f,i)=>{f.position.y=.35+Math.sin(t*.012+i)*.04*(move.lengthSq()?1:0)});speedEl.textContent=(move.length()*7*dash).toFixed(1);}
  if(targetTravel){player.position.lerp(targetTravel,1-Math.exp(-dt*3.8));if(player.position.distanceTo(targetTravel)<.3){targetTravel=null;}}
  const focus=player.position.clone().add(new THREE.Vector3(0,1.7,0));const behind=new THREE.Vector3(Math.sin(yaw)*camDistance,7.8,Math.cos(yaw)*camDistance);camera.position.lerp(focus.clone().add(behind),1-Math.exp(-dt*5));camera.lookAt(focus);world.update(dt,t/1000);placeLabels();const near=nearest();hint.classList.toggle('show',!!near&&!challenge.classList.contains('open'));if(near&&!challenge.classList.contains('open'))hint.textContent=`E · SCAN ${near.toUpperCase()}`;composer.render();}
requestAnimationFrame(loop);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.15:1.65));});
